name: app_seguridadmx
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.10.0
  permission_handler: ^11.0.1
  flutter_contacts: ^1.1.9+2
  image_picker: ^1.0.7
  file_picker: ^8.0.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4
  intl: ^0.18.1
  dio: ^5.9.2
  logger: ^2.7.0
  path_provider: ^2.1.5
  socket_io_client: ^3.1.4
  geolocator: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# Configuración del Generador de Iconos
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/fondoapp.png"
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/fondoapp.png"

flutter:
  uses-material-design: true

  # Declaración de la carpeta 
  assets:
    - assets/